//! Drops a TUNNEL_MANAGER.md instruction file into a deploy folder.
//! The file tells a developer how to adapt the project so that
//! Cloudflare Tunnel Manager can spawn it as a local server.

use std::path::{Path, PathBuf};
use crate::error::{AppError, AppResult};

pub const GUIDE_FILE: &str = "TUNNEL_MANAGER.md";

pub const GUIDE_CONTENT: &str = r##"# How to make this project work with Cloudflare Tunnel Manager

This file was generated by **Cloudflare Tunnel Manager** when the folder was
added as a deploy target. It documents the contract between your project and
the manager. Hand this to a teammate and they have
everything they need to wire the project in.

## What the manager does

When you toggle a page "on" in the manager, it:

1. Allocates a free TCP port on `127.0.0.1`.
2. Spawns your project's run command (the one in the page's "Run command"
   field) inside this folder.
3. Sets two environment variables for the child process:
   - `PORT` — the port number to bind to.
   - `HOST` — always `127.0.0.1`. Do NOT bind to `0.0.0.0` — the tunnel
     ships traffic from cloudflared (local) into your process, so localhost
     binding is the right scope.
4. Rewrites the page's `service_url` to `http://localhost:<PORT>` and
   restarts cloudflared with an updated ingress so your public hostname
   reaches this process.

When you toggle "off", the manager kills the process.

## Your project's job

**Bind to `process.env.PORT` (or the equivalent in your language), not a
hard-coded port.** If you hard-code, two pages on the same machine will
collide.

**Bind to `127.0.0.1`, not `0.0.0.0`.** This avoids exposing the raw HTTP
server to your LAN — cloudflared is the only thing that should talk to it.

**Exit cleanly on signal.** When the manager kills the proc (e.g.
`SIGTERM` on macOS/Linux, `TerminateProcess` on Windows), free resources,
flush logs, close file handles.

## Per-stack examples

### Node + Express

```js
const express = require('express');
const app = express();
const PORT = parseInt(process.env.PORT || '3000', 10);
const HOST = process.env.HOST || '127.0.0.1';

app.get('/', (req, res) => res.send('hello'));

app.listen(PORT, HOST, () => {
  console.log(`listening on http://${HOST}:${PORT}`);
});
```

In `package.json`:

```json
{
  "scripts": {
    "start": "node server.js"
  }
}
```

Manager auto-detects `npm start`.

### Node + Next.js

```json
{
  "scripts": {
    "start": "next start -H 127.0.0.1 -p $PORT"
  }
}
```

On Windows the `$PORT` substitution differs; if you hit issues, use:

```json
"start": "next start -H 127.0.0.1 -p %PORT%"
```

### Static site (plain HTML / built React / Vite output)

No code changes. Manager auto-detects and runs:

```
npx --yes serve -p {PORT} -L .
```

Set the page's "Folder" to the directory that contains `index.html`.

### Python + Flask

```python
import os
from flask import Flask
app = Flask(__name__)

@app.get("/")
def index():
    return "hello"

if __name__ == "__main__":
    port = int(os.environ.get("PORT", "3000"))
    app.run(host="127.0.0.1", port=port)
```

Run command: `python main.py`

### Python + FastAPI / Uvicorn

Run command (no code change to your app):

```
uvicorn main:app --host 127.0.0.1 --port {PORT}
```

### Go

```go
addr := "127.0.0.1:" + os.Getenv("PORT")
log.Fatal(http.ListenAndServe(addr, mux))
```

Build first, then run command: `./yourbinary`.

### Anything else

Whatever your server is, replace its bound port with `process.env.PORT` /
`os.environ['PORT']` / `getenv("PORT")` / etc. and put the command that
launches it in the manager's "Run command" field. Use `{PORT}` as a
placeholder anywhere on the command line if your launcher accepts a port
flag (the manager substitutes the literal port number at spawn time):

```
my-server --port {PORT} --bind 127.0.0.1
```

## Things to remove if migrating from a manual setup

If this folder used to be launched by a `iniciar.bat` / `start.sh` /
`docker-compose` / `pm2`, you can keep those for offline development but
**do not run them at the same time as the manager** — they fight for the
same cloudflared tunnel and your hostname will flap.

Specifically remove or disable any of these from your launcher when using
the manager:

- `cloudflared tunnel ... run` — the manager owns cloudflared.
- Hard-coded `PORT=3000` — the manager picks the port.
- DNS routing via `cloudflared tunnel route dns` — the manager does this
  through the Cloudflare API on save.

## Health check

The manager's Health view pings your service URL with a 2s timeout. If
your app needs longer than 2s to come up after spawn, the first few checks
will fail until the bind completes. Status will recover automatically once
the server is listening.

## Logs

Anything your process writes to stdout / stderr is captured by the
manager into a 2000-line ring buffer per page. View it from the manager's
Logs view (per-tunnel) or in the dev console for the local-server logs
(via the `get_local_logs` IPC).

## Project info this file documents

- Generated by: Cloudflare Tunnel Manager
- Contract version: 1
- Required env vars: `PORT`, `HOST`
- Forbidden behaviors: binding to `0.0.0.0`, hard-coded ports, owning its
  own cloudflared instance.
"##;

pub fn write_setup_guide(dir: &Path) -> AppResult<PathBuf> {
    if !dir.exists() {
        return Err(AppError::Other { message: format!("folder not found: {}", dir.display()) });
    }
    let path = dir.join(GUIDE_FILE);
    std::fs::write(&path, GUIDE_CONTENT).map_err(|e| AppError::Other {
        message: format!("write {}: {e}", path.display())
    })?;
    Ok(path)
}
